services:
  database:
    image: postgres:18.1
    container_name: libreledger_db
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  database_test:
    image: postgres:18.1
    container_name: libreledger_db_test
    restart: unless-stopped
    env_file:
      - ../.test.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql


volumes:
  postgres_data:
  postgres_test_data: