services:
  mariadb:
    image: mariadb:lts-ubi9
    container_name: libreledger_mariadb
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
 